# Generated by Django 3.2.3 on 2021-05-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0004_alter_warehouseitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='rack',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
