# Generated by Django 3.2.3 on 2021-05-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0005_warehouseitem_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_number', models.CharField(choices=[('1', 'Rack #1'), ('2', 'Rack #2')], default='1', max_length=2)),
                ('shelf', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tgclient.rack'),
        ),
    ]
