# Generated by Django 3.2.3 on 2021-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0006_auto_20210516_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='section',
            field=models.TextField(default='', verbose_name='section name'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(choices=[('1', '#1'), ('2', '#2'), ('3', '#3'), ('4', '#4'), ('5', '#5'), ('6', '#6'), ('7', '#7'), ('8', '#8'), ('9', '#9')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='rack',
            name='shelf',
            field=models.CharField(choices=[('1', '#1'), ('2', '#2'), ('3', '#3'), ('4', '#4'), ('5', '#5'), ('6', '#6'), ('7', '#7'), ('8', '#8'), ('9', '#9')], default='1', max_length=2),
        ),
    ]
