# Generated by Django 3.2.3 on 2021-05-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0007_auto_20210516_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='', verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(default='', verbose_name='User name'),
        ),
    ]
