# Generated by Django 3.2.3 on 2021-05-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0008_auto_20210517_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default='', unique=True, verbose_name='Item Name'),
        ),
    ]
