# Generated by Django 3.2.3 on 2021-05-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0009_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
    ]
