# Generated by Django 3.2.3 on 2021-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0010_alter_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Item Name'),
        ),
    ]
