# Generated by Django 3.2.3 on 2021-05-31 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0013_alter_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары (наименования)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='rack',
            options={'verbose_name': 'Стеллаж', 'verbose_name_plural': 'Стеллажи'},
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'verbose_name': 'Товар со склада', 'verbose_name_plural': 'Товары склада'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default='', verbose_name='никнейм'),
        ),
        migrations.AlterField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tgclient.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='', verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(blank=True, default='', verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='rack_number',
            field=models.CharField(choices=[('1', 'С1'), ('2', 'С2'), ('3', 'С3'), ('4', 'С4'), ('5', 'С5'), ('6', 'С6'), ('7', 'С7'), ('8', 'С8'), ('9', 'С9')], default='1', max_length=2, verbose_name='стеллаж №'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='section',
            field=models.CharField(choices=[('1', 'М1'), ('2', 'М2'), ('3', 'М3')], default='1', max_length=2, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='shelf',
            field=models.CharField(choices=[('1', 'П1'), ('2', 'П2'), ('3', 'П3'), ('4', 'П4'), ('5', 'П5'), ('6', 'П6'), ('7', 'П7'), ('8', 'П8'), ('9', 'П9')], default='1', max_length=2, verbose_name='полка'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('СК', 'Склад'), ('ОЖ', 'Ожидается')], default='СК', max_length=2),
        ),
    ]
