# Generated by Django 3.2.3 on 2021-06-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0014_auto_20210531_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='receipt_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата прибытия'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgclient.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tgclient.rack', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('СК', 'Склад'), ('ОЖ', 'Ожидается')], default='СК', max_length=2, verbose_name='статус'),
        ),
    ]
