# Generated by Django 3.2.3 on 2021-06-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0015_auto_20210601_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='receipt_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прибытия'),
        ),
    ]
