# Generated by Django 3.2.3 on 2021-06-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0016_alter_warehouseitem_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='receipt_date',
            field=models.DateField(verbose_name='Дата прибытия'),
        ),
    ]
