# Generated by Django 3.2.3 on 2021-06-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0019_alter_warehouseitem_receipt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='status',
            field=models.CharField(choices=[('102', 'Склад'), ('ОЖ', 'Ожидается'), ('100', '100'), ('108', '108'), ('206', '206')], default='102', max_length=3, verbose_name='статус'),
        ),
    ]
