# Generated by Django 3.2.3 on 2021-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0021_alter_warehouseitem_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='receipt_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата прибытия'),
        ),
    ]
