# Generated by Django 3.2.3 on 2021-06-01 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0025_alter_warehouseitem_rack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_section', to='tgclient.rack', verbose_name='Место'),
        ),
    ]
