# Generated by Django 3.2.3 on 2021-06-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0028_auto_20210603_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rack',
        ),
    ]
