# Generated by Django 3.2.3 on 2021-06-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0029_delete_rack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '1. Наименования'},
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '2. Товары'},
        ),
    ]
