# Generated by Django 3.2.3 on 2021-06-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgclient', '0030_auto_20210603_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/'),
        ),
    ]
